removed normalize-before
articulatory/articulatory pull request #1
Opened 2023-07-20 04:32 UTC by olafbrah

-removed references to the normalize-before parameter
-uncommented default to cpu because I am using a mac

2023-07-23 22:41 UTC, peter-yh-wu requested changes

2023-07-23 22:41 UTC, peter-yh-wu commented on egs/ema/voc1/local/predict_wav.py
> +    # if args.normalize_before:
These can be deleted too

2023-07-23 22:41 UTC, peter-yh-wu commented on egs/ema/voc1/local/predict_wav.py
> +            c = np.load(featp, allow_pickle=True)
allow_pickle not needed

2023-07-28 02:45 UTC, olafbrah reviewed
added fixes

2023-07-28 17:25 UTC, peter-yh-wu approved these changes

2023-07-28 17:25 UTC, merged